export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  asdf
  brew
  direnv
  docker
  docker-compose
  fasd
  git
  jsontools
  npm
  terraform
  vscode
  zsh-autosuggestions
  zsh-syntax-highlighting
  history-substring-search
)

source $ZSH/oh-my-zsh.sh
